export const ADIC_INGREDIENTE = 'ADIC_INGREDIENTE'
export const REMOV_INGREDIENTE = 'REMOV_INGREDIENTE'
export const SET_INGREDIENTES = 'SET_INGREDIENTES'
export const BUSCAR_INGREDIENTES_ERRO = 'BUSCAR_INGREDIENTES_ERRO'


